### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by stepir** [jonathan-fielding/homebridge-yalealarmsystem#4]
Hey Jonathan,

It doesn't look you are still active on this but I thought I'd give a try and ask - any chance you could implement support for the following accessories of a Yale alarm system:

- Yale Room Temperature Sensor
- Yale Smart Living SR-PS Smart Plug

Thanks
Stefano

**Comment by jonathan-fielding** [comment]
@stepir unfortunately I can't implement functionality for devices I do not own, happy to accept pull requests tho
